house:
  name: Andy Shen
  email: andy@shenie.info
mini:
  name: Andy Shen
  email: andy@shenie.info
  mappings:
    .bashrc: <%= PRIVATE_DIR %>/mini.bashrc
    <%= ENV['NGINX_HOME'] %>/conf/nginx.conf: <%= PRIVATE_DIR %>/nginx/nginx.conf
foxy:
  name: Jackie Chu
  email: jackie@shenie.info

mappings:
  .bash_profile: <%= PRIVATE_DIR %>/<%= HOST %>.profile.rc
  .gitconfig: <%= GENERATED_DIR %>/gitconfig
  .irbrc: <%= PUBLIC_DIR %>/ruby/irbrc
  .sqliterc: <%= PUBLIC_DIR %>/sqliterc
  .vim: <%= PUBLIC_DIR %>/vim
  .vimrc: <%= PUBLIC_DIR %>/vimrc
  .gvimrc: <%= PUBLIC_DIR %>/gvimrc 
  .rakelib: <%= PUBLIC_DIR %>/rakelib
  .private.rc: <%= PRIVATE_DIR %>/profile.rc
  .public.rc: <%= PUBLIC_DIR %>/profile.rc
  .git-completion.sh: <%= PUBLIC_DIR %>/git/git-completion.sh
  bin/jad: <%= BIN_DIR %>/jadmx158/jad
  bin/vlc-play: <%= BIN_DIR %>/vlc/play
  bin/vlc-mute: <%= BIN_DIR %>/vlc/mute
  bin/vlc-louder: <%= BIN_DIR %>/vlc/louder
  bin/vlc-softer: <%= BIN_DIR %>/vlc/softer
  bin/vlc-next: <%= BIN_DIR %>/vlc/next
  bin/vlc-previous: <%= BIN_DIR %>/vlc/previous
  bin/jruby: <%= HOME %>/dev/tools/jruby/bin/jruby
 
