set nocompatible                  " Must come first because it changes other options.

if has("gui_macvim")
  colorscheme ir_black
  set lines=60
  set columns=140
  set guifont=Menlo_Regular:h13
  if $SHELL =~ '/\(sh\|csh\|bash\|tcsh\|zsh\)$'
    let s:path = system("echo echo VIMPATH'${PATH}' | $SHELL -l")
    let $PATH = matchstr(s:path, 'VIMPATH\zs.\{-}\ze\n')
  endif
  macmenu &File.New\ Tab key=<nop>
  map <D-t> <Plug>PeepOpen
endif

silent! call pathogen#runtime_append_all_bundles()

syntax on
set noautoindent

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set history=1000

set wrap                          "wrap lines
set linebreak                     "wrap lines at convenient points

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set tabstop=2                     " Global tab width.
set shiftwidth=2                  " And again, related.
set expandtab                     " Use spaces instead of tabs

set background=dark

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location

set statusline=%<[%n]\ %F\ %h%m%r%=%-14.(%l,%c%V%)\ %P
set laststatus=2                  " Show the status line all the time

set foldcolumn=2
"autocmd FileType ruby setlocal foldmethod=syntax
"This changes directory but it is like autochdir
"autocmd BufEnter * silent! lcd %:p:h:gs/ /\\ /

